import Head from "next/head";
import { Feed } from "../components/Feed";
import { Sidebar } from "../components/Sidebar";
import { Widgets } from "../components/Widgets";

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-automx-16">
        {/* Sidebar */}
        <Sidebar></Sidebar>

        {/* Feed */}
        <Feed></Feed>

        {/* Widgets */}
        <Widgets
          newsResults={props.newsResults.articles}
          randomUsersResults={props.randomUsersResults.results}
        ></Widgets>

        {/* Modal */}
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  // News results
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  // Who to follow section
  const randomUsersResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
}
