import Head from "next/head";
import { Sidebar } from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-automx-16">
        {/* Sidebar */}
        <Sidebar></Sidebar>

        {/* Feed */}

        {/* Widgets */}

        {/* Modal */}
      </main>
    </div>
  );
}
